Pull request for code review - Reviewing Hello Microverse code
wickathou/hello-microverse pull request #2
Opened 2022-11-29 15:21 UTC by wickathou

This pull request was created to review the structure and workflow followed while making this project. The final pull request authorizes the merger of the last feature branch, which is a revert of a wrongly submitted pull request and the merger with the main branch

2022-11-29 15:48 UTC, mukhammadrizooff requested changes
Hi @wickathou, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

<img src="https://media4.giphy.com/media/Jq824R93JsLwZCaiSL/giphy.gif"/>

## Highlights
- Descriptive Pull Request summary ✔️ 
- Good implementations ✔️ 

## Required Changes ♻️
- [ ] [REQUIRED] Please implement my suggestions! You forgot to install `Linter Actions`, please install them [based on the list](https://github.com/microverseinc/linters-config/tree/master/html-css) provided by `Microverse` 🙏 

![image](https://user-images.githubusercontent.com/63915024/204576469-bcf2fa65-7423-4533-8405-e70c7ef8fbba.png)

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-11-29 15:52 UTC, mukhammadrizooff requested changes
Hi @wickathou, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

<img src="https://media4.giphy.com/media/Jq824R93JsLwZCaiSL/giphy.gif"/>

## Highlights
- Descriptive Pull Request summary ✔️ 
- Good implementations ✔️ 

## Required Changes ♻️
- [ ] [REQUIRED] Please implement my suggestions! You forgot to install `Linter Actions`, please install them [based on the list](https://github.com/microverseinc/linters-config/tree/master/html-css) provided by `Microverse` 🙏 

![image](https://user-images.githubusercontent.com/63915024/204576469-bcf2fa65-7423-4533-8405-e70c7ef8fbba.png)

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-11-29 15:52 UTC, mukhammadrizooff commented on README.md
> +Hello world to microverse
- [ ] [REQUIRED] Good job so far! Please Implement descriptive `README` [provided by Microverse](https://github.com/microverseinc/readme-template) 🙏

2022-11-30 14:07 UTC, wickathou commented
@mukhammadrizooff I had to close this PR, because I made a mess of it! I''ll remake a new PR

2022-11-30 14:08 UTC, merged